version: "3"

x-uffizzi:
  ingress:
    service: metabase
    port: 3000

services:
  metabase:
   image: "${METABASE_IMAGE}"
   deploy:
      resources:
        limits:
          memory: 250M
   restart: always
   ports:
     - "3000:3000"