version: "3"

x-uffizzi:
  ingress:
    service: metabase
    port: 3000

services:
  metabase:
   image: "${METABASE_IMAGE}"
   deploy:
      resources:
        limits:
          memory: 250M
   restart: always
   ports:
     - "3000:3000"

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: